imr_arm1:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: Joint1       #Must have the same name as the associated joint in your urdf file
        pid: {p: 100.0, i: 0.01, d: 10}
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: Joint2       #Must have the same name as the associated joint in your urdf file
        pid: {p: 100.0, i: 0.01, d: 10}
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: Joint3       #Must have the same name as the associated joint in your urdf file
        pid: {p: 100.0, i: 0.01, d: 10}
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: Joint4       #Must have the same name as the associated joint in your urdf file
        pid: {p: 100.0, i: 0.01, d: 10}
    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: Joint5       #Must have the same name as the associated joint in your urdf file
        pid: {p: 100.0, i: 0.01, d: 10}